### ISSUE TITLE
 Consider adding Memo_Field_Required Flag

### ISSUE THREAD

**Issue by michaelran16** [stellar/stellar-protocol#341] opened 2019-07-04 20:14 UTC
## Background

There has been ongoing requests from wallets and exchanges about this. Users not putting in "Memo" when transferring XLMs sometimes wait a long time for their fund to show up. Example discussions in the community: 

https://www.reddit.com/r/Stellar/comments/7fei7r/missing_xlm_deposit_in_bittrex_due_to_no_tagmemo/
https://www.reddit.com/r/Stellar/comments/b8tddt/incorrect_memo_tag_from_stellar_wallet_coinbase/

## Suggestion

While I understand that using the federation model can solve this issue, many wallets or exchanges are not implementing it yet. For some reason, most exchanges use 1 single Stellar address for receiving XLM deposit. If "Memo" is blank, customer support needs to step in and do manual verification. 

Adding Memo_Field_Required flag would help reduce a lot of confusions when people try deposit XLM into exchanges using a centralized stellar address. Shall we consider adding this into next SEP?

**Comment by tomerweller** [comment] 2019-07-08 04:35
@michaelran16 can you give some more information about how something like this would work? (maybe the [stellar-dev](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/stellar-dev/LIFvbMi9jPo) mailing list is a better place to discuss) 

I agree that this is a problem and getting exchanges to use federated addresses is an uphill battle, which we're losing. While such a flag might solve most of the issues, it still doesn't address issues caused by people typing in the wrong memo, or putting in the wrong type. I'd rather see a general purpose "sign to receive" feature which can allow services to actually verify that the memo makes sense before accepting it.

**Comment by MonsieurNicolas** [comment] 2019-07-08 16:16
This is a dupe of https://github.com/stellar/stellar-protocol/issues/71

**Closed** 2019-07-08 16:38 UTC
